import {Scope,module,num,numeric,wrap,unwrap,inspect,nativeCall,nativeOwner,isPromiseLike,portableBuiltin} from './values.mjs';
import {WasmRuntime} from './wasm.mjs';
import {BrowserWgpuBackend} from './wgpu.mjs';
import {BrowserJoltBackend,vector,number} from './physics.mjs';
import {Processing,pack} from './processing.mjs';
import {mat4,vec3} from './vendor-gl-matrix.mjs';
import {registerLegacy} from './legacy.mjs';
import {resolvePath,lookupPath} from './package-paths.mjs';
import {BrowserSurface} from './surface.mjs';
import {BrowserApplication} from './application.mjs';
export class BrowserHost {
  constructor(bundle,{signal=new AbortController().signal,frameLimit=0,print=console.log}={}) {
    if(bundle.version!==2)throw new Error('Unsupported website version');this.bundle=bundle;this.signal=signal;this.frameLimit=frameLimit;this.print=print;this.modules=new Map();this.objects=new Map();this.cache=new Map();this.importing=new Set();this.downloads=new Map();this.graphics=new BrowserWgpuBackend(bundle.graphics);this.physics=new BrowserJoltBackend();this.builtins=new Map();this.runtime=new WasmRuntime(this);this.register();
  }
  newModule(){return module(new Scope());}
  set(m,n,v){m.scope.create(n,wrap(v));}
  bind(m,library,name,fn,raw=false){const aliases={PVector:'Processing.Vector',PImage:'Processing.Image',PShape:'Processing.Shape',PShader:'Processing.Shader'},lib=aliases[library]??library;const item=this.bundle.catalog.find(f=>f.library===lib&&f.english===name)??this.bundle.catalog.find(f=>f.english===name);const entry=(...a)=>{if(this.signal.aborted)throw new Error('Execution cancelled');if(item&&(a.length<item.min||a.length>item.max))throw new Error(`${library}.${name}: Expected ${item.min}..${item.max} arguments, got ${a.length}`);const result=fn(...(raw?a:a.map(unwrap)));return isPromiseLike(result)?Promise.resolve(result).then(value=>raw?value:wrap(value)):raw?result:wrap(result);};const callable=async(...a)=>entry(...a);callable[nativeCall]=entry;callable[nativeOwner]=m;m.scope.create(name,callable);if(item?.chinese)m.scope.create(item.chinese,callable);return callable;}
  library(name){const m=this.newModule();this.modules.set(name,m);return m;}
  builtinsFor(path){const map=new Map(this.builtins),cwd='/'+path.split('/').slice(0,-1).join('/');map.set('目前工作目錄',cwd);map.set('currWorkingDir',cwd);const fn=this.globalImport(path);map.set('import',fn);map.set('匯入',fn);return map;}
  globalImport(path){return async name=>{if(typeof name!=='string')throw new Error('import expects a string');if(this.modules.has(name))return this.modules.get(name);const full=lookupPath(this.bundle.modules,this.resolve(name,path),{module:true});if(this.importing.has(full))throw new Error(`Circular import: ${full}`);this.importing.add(full);try{const env=new Scope();await this.runtime.execute(this.bundle.modules[full],env,this.builtinsFor(full));const m=module(env);this.cache.set(full,m);this.cache.set(full.replace(/\.aqua$/i,'.aqua'),m);return m;}finally{this.importing.delete(full);}};}
  resolve(name,path=''){return resolvePath(name,path);}
  async execute(entry){entry=lookupPath(this.bundle.modules,this.resolve(entry),{module:true});if(this.importing.has(entry))throw new Error(`Circular import: ${entry}`);this.importing.add(entry);try{return await this.runtime.execute(this.bundle.modules[entry],new Scope(),this.builtinsFor(entry));}finally{this.importing.delete(entry);}}
  register(){const globals=this.newModule(),b=(n,f,raw=false)=>this.bind(globals,'',n,f,raw);
    b('len',v=>num(typeof v==='string'?v.length:Array.isArray(v)?v.length:(()=>{throw new Error('len expects string or array');})(),'int'),true);b('last',v=>{if(!Array.isArray(v))throw new Error('last expects array');return v.at(-1)??null;},true);b('rest',v=>{if(!Array.isArray(v))throw new Error('rest expects array');return v.length?v.slice(1):null;},true);b('push',(a,v)=>{if(!Array.isArray(a))throw new Error('push expects array');return [...a,v];},true);b('print',(...a)=>{this.print(a.map(inspect).join(' '));},true);for(const n of ['isOSWindows','isOSLinux','isOSMacOS'])b(n,()=>false);b('execFile',()=>{throw new Error('execFile requires a desktop host');});this.builtins=new Map(globals.scope.store);
    for(const [name,id]of [['len',1],['last',2],['rest',3],['push',4]])this.builtins.get(name)[portableBuiltin]=id;
    this.processing=new Processing(this);this.modules.set('Processing',this.processing.module);this.registerGpu();this.registerPhysics();this.registerMath();this.registerText();registerLegacy(this);
    this.application=new BrowserApplication(this);
  }
  registerGpu(){const m=this.library('WGPU');this.modules.set('wgpu',m);this.set(m,'Backend','webgpu');this.bind(m,'WGPU','CreateDevice',async()=>{
    const d=await this.graphics.createDevice(),dm=this.newModule();this.objects.set(dm,d);this.set(dm,'Backend',d.backend);const b=(n,f)=>this.bind(dm,'WGPU.Device',n,f);b('Dispose',()=>d.dispose());b('Poll',()=>d.poll());
    b('CreateBuffer',values=>{if(!Array.isArray(values)||!values.length||values.length>16*1024*1024||values.some(v=>typeof v!=='number'||!Number.isFinite(v)||!Number.isFinite(Math.fround(v))))throw new Error('wgpu data needs finite floats');d.live();const buffer=d.createBuffer(values),bm=this.newModule();this.objects.set(bm,buffer);this.set(bm,'Length',num(buffer.length,'int'));this.bind(bm,'WGPU.Buffer','Write',v=>buffer.write(v));this.bind(bm,'WGPU.Buffer','Read',()=>buffer.read());this.bind(bm,'WGPU.Buffer','Dispose',()=>buffer.dispose());return bm;});
    b('Dispatch',(source,buffer,groups)=>{if(!Number.isInteger(groups)||groups<1||groups>65535)throw new Error('Workgroup count must be 1..65535');const obj=this.objects.get(buffer);if(!obj||obj.owner!==d)throw new Error('Expected a live buffer from this wgpu device');return d.dispatch(source,obj,groups);});
    b('CreateShader',async(v,f)=>{const shader=await d.createShader(v,f),sm=this.newModule();this.objects.set(sm,shader);this.bind(sm,'WGPU.Shader','Set',(n,v)=>shader.set(n,v));this.bind(sm,'WGPU.Shader','SetInt',(n,v)=>shader.set(n,[v],true));this.bind(sm,'WGPU.Shader','Dispose',()=>shader.dispose());return sm;});
    b('CreateRenderTarget',(w,h)=>{const target=d.createTarget(w,h),tm=this.newModule();this.set(tm,'Width',num(w,'int'));this.set(tm,'Height',num(h,'int'));this.bind(tm,'WGPU.Target','Clear',c=>{if(!Array.isArray(c)||c.length!==4||c.some(v=>!Number.isFinite(v)||v<0||v>1))throw new Error('Color needs four RGBA values in 0..1');target.clear(c);});this.bind(tm,'WGPU.Target','Draw',(shader,vertices)=>{if(!Array.isArray(vertices)||vertices.length===0||vertices.length%36||vertices.some(v=>!Number.isFinite(v)))throw new Error('Triangle vertices need a multiple of 36 finite floats');const obj=this.objects.get(shader);if(!obj)throw new Error('Expected a live shader');target.draw(obj,vertices);});this.bind(tm,'WGPU.Target','ReadPixels',async()=>{const bytes=await target.readPixels();return Array.from({length:bytes.length/4},(_,i)=>pack(Array.from(bytes.subarray(i*4,i*4+4),v=>v/255)));});this.bind(tm,'WGPU.Target','Save',async path=>this.saveImage(path,w,h,await target.readPixels()));this.bind(tm,'WGPU.Target','Dispose',()=>target.dispose());return tm;});return dm;
  });}
  registerPhysics(){const m=this.library('Jolt');this.modules.set('JoltPhysics',m);this.set(m,'Backend',this.physics.name);this.set(m,'MaxBodies',num(this.bundle.physics.maxBodies,'int'));this.bind(m,'Jolt','CreateWorld',async gravity=>{const world=await this.physics.createWorld(gravity),wm=this.newModule(),b=(n,f)=>this.bind(wm,'Jolt.World',n,f);b('Dispose',()=>world.dispose());b('GetBodyCount',()=>{world.live();return num(world.bodies.size,'int');});b('GetGravity',()=>world.getGravity());b('SetGravity',v=>world.setGravity(v));b('CreateSphere',(r,p,m)=>world.create('sphere',r,p,m));b('CreateBox',(half,p,m)=>world.create('box',half,p,m));b('Step',(dt,steps)=>world.step(dt,steps));b('RemoveBody',body=>world.remove(body));b('OptimizeBroadPhase',()=>{world.live();world.system.OptimizeBroadPhase();});for(const n of ['GetPosition','GetRotation','GetLinearVelocity','GetAngularVelocity','IsActive'])b(n,body=>world.get(n,body));for(const n of ['SetPosition','SetRotation','SetLinearVelocity','SetAngularVelocity','AddForce','AddImpulse','AddAngularImpulse','SetFriction','SetRestitution'])b(n,(body,v)=>world.set(n,body,v));return wm;});}
  registerMath(){const m=this.library('GLM'),b=(n,f)=>this.bind(m,'GLM',n,f);this.set(m,'PI',Math.PI);b('Radians',n=>n*Math.PI/180);b('Sin',Math.sin);b('Cos',Math.cos);b('Sqrt',Math.sqrt);b('Dot',vec3.dot);b('Cross',(a,b)=>Array.from(vec3.cross(vec3.create(),a,b)));b('Normalize',a=>{vector(a);if(!Math.hypot(...a))throw new Error('Cannot normalize zero vector');return Array.from(vec3.normalize(vec3.create(),a));});b('Identity',()=>Array.from(mat4.create()));b('Translate',v=>Array.from(mat4.fromTranslation(mat4.create(),v)));b('Scale',v=>Array.from(mat4.fromScaling(mat4.create(),v)));b('Rotate',(angle,axis)=>Array.from(mat4.fromRotation(mat4.create(),angle,axis)));b('Multiply',(a,b)=>Array.from(mat4.multiply(mat4.create(),a,b)));b('LookAt',(e,t,u)=>Array.from(mat4.lookAt(mat4.create(),e,t,u)));b('Perspective',(f,a,n,z)=>Array.from(mat4.perspectiveNO(mat4.create(),f,a,n,z)));b('Transpose',a=>Array.from(mat4.transpose(mat4.create(),a)));b('Inverse',a=>{const out=mat4.invert(mat4.create(),a);if(!out)throw new Error('Matrix is singular');return Array.from(out);});b('TransformPoint',(m,v)=>Array.from(vec3.transformMat4(vec3.create(),v,m)));}
  registerText(){const m=this.library('TextInput');this.bind(m,'TextInput','Backspace',text=>{const segments=[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(text)];return segments.slice(0,-1).map(s=>s.segment).join('');});this.bind(m,'TextInput','Length',text=>num([...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(text)].length,'int'));}
  surface(w,h,title){return new BrowserSurface(document.getElementById('surfaces'),w,h,title);}
  async nextFrame(fps=60){const start=performance.now();await new Promise(r=>requestAnimationFrame(r));const remaining=1000/fps-(performance.now()-start);if(remaining>1)await new Promise(r=>setTimeout(r,remaining));}
  asset(path){const name=lookupPath(this.bundle.assets,this.resolve(path));return Uint8Array.from(atob(this.bundle.assets[name]),c=>c.charCodeAt(0));}
  async imageBytes(path){const bytes=this.asset(path);if(path.endsWith('.ppm')){let pos=0;const token=()=>{while(pos<bytes.length){if(bytes[pos]===35){while(pos<bytes.length&&bytes[pos]!==10)pos++;}else if(bytes[pos]<=32)pos++;else break;}const start=pos;while(pos<bytes.length&&bytes[pos]>32)pos++;return new TextDecoder().decode(bytes.subarray(start,pos));};const format=token(),width=Number(token()),height=Number(token()),max=Number(token());if(!['P3','P6'].includes(format)||max>255||max<1)throw new Error('Unsupported PPM format');const out=new Uint8Array(width*height*4);if(format==='P6'){if(bytes[pos]===13&&bytes[pos+1]===10)pos+=2;else pos++;for(let i=0;i<width*height;i++)out.set([bytes[pos+i*3]*255/max,bytes[pos+i*3+1]*255/max,bytes[pos+i*3+2]*255/max,255],i*4);}else for(let i=0;i<width*height;i++)out.set([Number(token())*255/max,Number(token())*255/max,Number(token())*255/max,255],i*4);return {width,height,bytes:out};}const img=await createImageBitmap(new Blob([bytes])),c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);img.close();return {width:c.width,height:c.height,bytes:ctx.getImageData(0,0,c.width,c.height).data};}
  async saveImage(path,w,h,bytes){const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(bytes),w,h),0,0);const blob=await new Promise(r=>c.toBlob(r,'image/png'));this.downloads.set(path,blob);if(!this.frameLimit){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=path.split('/').at(-1);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}
  async dispose(){this.runtime.cancelled=true;try{await this.application.dispose();}finally{this.processing.dispose();this.physics.dispose();this.graphics.dispose();this.legacyDispose?.();}}
}
