import {num,unwrap} from './values.mjs';
// The existing OpenGL example maps to WebGL2. Processing and WGPU use WebGPU.
export function registerLegacy(h){const glfw=h.library('GLFW'),glad=h.library('GLAD'),gl=h.library('GL'),stb=h.library('STBImage');let surface,canvas,context,closed=false,frames=0;const resources=new Set(),requireGl=()=>{if(!context)throw new Error('Call GLFW.CreateWindow first');return context;},b=(m,lib,n,fn,raw=false)=>h.bind(m,lib,n,fn,raw);
  const resize=()=>{if(surface)surface.apply(surface.readSize());};
  b(gl,'GL','ReadText',path=>new TextDecoder().decode(h.asset(path)));
  b(gl,'GL','ReadBytes',path=>Array.from(h.asset(path)));
  for(const [n,v] of Object.entries({GLFW_PRESS:1,GLFW_RELEASE:0,GLFW_KEY_ESCAPE:256,GLFW_KEY_SPACE:32,GLFW_SAMPLES:0x2100d,GLFW_CONTEXT_VERSION_MAJOR:0x22002,GLFW_CONTEXT_VERSION_MINOR:0x22003,GLFW_OPENGL_PROFILE:0x22008,GLFW_OPENGL_CORE_PROFILE:0x32001}))h.set(glfw,n,num(v,'int'));
  b(glfw,'GLFW','Init',()=>true);b(glfw,'GLFW','WindowHint',()=>{});b(glfw,'GLFW','CreateWindow',(w,hh,title)=>{surface=h.surface(w,hh,title);surface.requestSize(w,hh);canvas=surface.canvas;context=canvas.getContext('webgl2',{antialias:true,preserveDrawingBuffer:true});if(!context)throw new Error('WebGL2 unavailable');closed=false;frames=0;for(const n of Object.keys(h.bundle.legacyConstants??{}))h.set(gl,n,h.bundle.legacyConstants[n]);for(const n of Object.keys(context))if(n===n.toUpperCase()&&typeof context[n]==='number')h.set(gl,'GL_'+n,context[n]);return {type:'GLFW_WINDOW',canvas};});
  b(glfw,'GLFW','MakeContextCurrent',()=>{});b(glad,'GLAD','Load',()=>true);b(glfw,'GLFW','SwapInterval',()=>{});b(glfw,'GLFW','GetTime',()=>performance.now()/1000);b(glfw,'GLFW','GetEnvironment',name=>name==='AQUARIUS_GRAPHICS_FRAMES'?h.frameLimit?String(h.frameLimit):'':name==='AQUARIUS_GRAPHICS_CAPTURE'?'':'');b(glfw,'GLFW','PollEvents',resize);b(glfw,'GLFW','WindowShouldClose',()=>closed||h.signal.aborted);b(glfw,'GLFW','SetWindowShouldClose',(_,v)=>closed=v);b(glfw,'GLFW','GetKey',(_,code)=>num(h.processing.keys.has(code)?1:0,'int'));b(glfw,'GLFW','GetFramebufferSize',()=>[num(surface.size.pixelWidth,'int'),num(surface.size.pixelHeight,'int')]);b(glfw,'GLFW','GetWindowSize',()=>[num(surface.size.width,'int'),num(surface.size.height,'int')]);b(glfw,'GLFW','SetWindowSize',(_,w,hh)=>surface.requestSize(w,hh));b(glfw,'GLFW','SwapBuffers',async()=>{frames++;if(h.frameLimit&&frames>=h.frameLimit)closed=true;await h.nextFrame();});b(glfw,'GLFW','DestroyWindow',()=>closed=true);b(glfw,'GLFW','Terminate',()=>closed=true);
  for(const [n,Type] of [['FloatData',Float32Array],['UIntData',Uint32Array],['ByteData',Uint8Array]])b(gl,'GL',n,a=>({type:'GL_DATA',bytes:new Type(a)}));b(gl,'GL','Allocate',n=>({type:'GL_DATA',bytes:new Uint8Array(n)}));b(gl,'GL','ByteLength',data=>num(data.bytes.byteLength,'int'));b(gl,'GL','FreeData',()=>{});b(gl,'GL','ParseInteger',s=>num(Number.parseInt(s,10),'int'));
  const kinds={Buffers:'Buffer',VertexArrays:'VertexArray',Textures:'Texture',Framebuffers:'Framebuffer',Renderbuffers:'Renderbuffer'};
  for(const [plural,singular] of Object.entries(kinds)){b(gl,'GL',`glGen${plural}`,(count,array)=>{count=unwrap(count);for(let i=0;i<count;i++){const obj=requireGl()[`create${singular}`]();resources.add([singular,obj]);array[i]=obj;}},true);b(gl,'GL',`glDelete${plural}`,(count,array)=>{for(let i=0;i<count;i++)requireGl()[`delete${singular}`](array[i]);});}
  const shader=(type,source)=>{const g=requireGl(),s=g.createShader(type);source=source.replace(/#version\s+330\s+core/g,'#version 300 es');if(type===g.FRAGMENT_SHADER)source=source.replace(/#version 300 es/,'#version 300 es\nprecision highp float;');g.shaderSource(s,source);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS)){const error=g.getShaderInfoLog(s);g.deleteShader(s);throw new Error(`Shader compile failed: ${error}`);}return s;};
  b(gl,'GL','CreateProgram',(v,f)=>{const g=requireGl(),vs=shader(g.VERTEX_SHADER,v),fs=shader(g.FRAGMENT_SHADER,f),p=g.createProgram();try{g.attachShader(p,vs);g.attachShader(p,fs);g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p));resources.add(['Program',p]);return p;}finally{g.deleteShader(vs);g.deleteShader(fs);}});
  b(gl,'GL','glGetString',n=>String(requireGl().getParameter(n)));b(gl,'GL','glBufferData',(target,size,data,usage)=>requireGl().bufferData(target,data?.bytes??size,usage));b(gl,'GL','glUniformMatrix4fv',(loc,count,transpose,v)=>requireGl().uniformMatrix4fv(loc,transpose,new Float32Array(v)));b(gl,'GL','glTexImage2D',(target,level,internal,w,hh,border,format,type,data)=>requireGl().texImage2D(target,level,internal,w,hh,border,format,type,data?.bytes??null));
  b(gl,'GL','glEnable',n=>{if(n!==32925)requireGl().enable(n);}); // GL_MULTISAMPLE is controlled at canvas creation.
  for(const n of ['glBindVertexArray','glBindBuffer','glVertexAttribPointer','glEnableVertexAttribArray','glUseProgram','glActiveTexture','glBindTexture','glGenerateMipmap','glTexParameteri','glGetUniformLocation','glUniform1i','glUniform1f','glUniform2f','glUniform3f','glUniform4f','glViewport','glClearColor','glClear','glDrawElements','glDrawArrays','glGetError','glDeleteProgram'])b(gl,'GL',n,(...a)=>{const name=n[2].toLowerCase()+n.slice(3),g=requireGl();const result=g[name](...a);return n==='glGetError'?num(result,'int'):result;});
  b(stb,'STBImage','Load',async(path,flip)=>{const image=await h.imageBytes(path);let bytes=image.bytes;if(flip){bytes=new Uint8Array(bytes.length);for(let y=0;y<image.height;y++)bytes.set(image.bytes.subarray(y*image.width*4,(y+1)*image.width*4),(image.height-1-y)*image.width*4);}return [num(image.width,'int'),num(image.height,'int'),num(4,'int'),{type:'GL_DATA',bytes}];});
  b(gl,'GL','SavePPM',async(path,w,hh)=>{const bytes=new Uint8Array(w*hh*4);requireGl().readPixels(0,0,w,hh,context.RGBA,context.UNSIGNED_BYTE,bytes);await h.saveImage(path,w,hh,bytes);});
  h.legacyDispose=()=>{if(context){for(const [kind,obj] of resources)context[`delete${kind}`](obj);context.getExtension('WEBGL_lose_context')?.loseContext();}surface?.dispose();closed=true;};
}
