import {mat4,vec3,vec4} from './vendor-gl-matrix.mjs';
import earcut from './vendor-earcut.mjs';
import {num,unwrap} from './vm.mjs';
import {defaultUniforms} from './wgpu.mjs';
import {resizeSurfaceSize} from './surface.mjs';
export const pack = c => ((Math.round(c[3]*255)<<24)|(Math.round(c[0]*255)<<16)|(Math.round(c[1]*255)<<8)|Math.round(c[2]*255))>>>0;
export const unpack = c => [(c>>>16&255)/255,(c>>>8&255)/255,(c&255)/255,(c>>>24)/255];
const clamp=(n,lo=0,hi=1)=>Math.max(lo,Math.min(hi,n)),mix=(a,b,t)=>a+(b-a)*t;
const hsb=(h,s,b,a)=>{h=(h-Math.floor(h))*6;const p=b*(1-s),q=b*(1-s*(h%1)),t=b*(1-s*(1-h%1));return [[b,t,p,a],[q,b,p,a],[p,b,t,a],[p,q,b,a],[t,p,b,a],[b,p,q,a]][Math.floor(h)];};
const style=()=>({fill:[1,1,1,1],stroke:[0,0,0,1],tint:[1,1,1,1],hasFill:true,hasStroke:true,weight:1,colorMax:[255,255,255,255],colorMode:0,rectMode:0,ellipseMode:2,imageMode:0,font:'sans-serif',textSize:12,leading:14,align:0,vertical:103,ambient:[.2,.2,.2],specular:[.25,.25,.25],emissive:[0,0,0],material:[1,1,1,16],lights:[],lit:false,lightSpecular:[0,0,0],falloff:[1,0,0]});
function color(s,a){const alpha=(a.length===2||a.length===4)?a.at(-1)/s.colorMax[3]:1;if(a.length<=2){if(a[0]>s.colorMax[2]){const c=unpack(a[0]);if(a.length===2)c[3]=alpha;return c;}return [a[0]/s.colorMax[2],a[0]/s.colorMax[2],a[0]/s.colorMax[2],alpha].map(x=>clamp(x));}const c=a.map((v,i)=>v/s.colorMax[i]);if(a.length===3)c.push(1);return (s.colorMode===1?hsb(...c):c).map(x=>clamp(x));}
function bounds(x,y,w,h,m){return m===1?[x,y,w-x,h-y]:m===2?[x-w/2,y-h/2,w,h]:m===3?[x-w,y-h,w*2,h*2]:[x,y,w,h];}
const point=(a,d=2)=>[a[0],a[1],d===3?a[2]:0];
const bez=(a,b,c,d,t)=>{const s=1-t;return s*s*s*a+3*s*s*t*b+3*s*t*t*c+t*t*t*d;};
const curve=(a,b,c,d,t)=>bez(b,b+(c-a)/6,c-(d-b)/6,c,t);
const keyCode=e=>({Escape:256,Enter:257,Tab:258,Backspace:259,Insert:260,Delete:261,ArrowRight:262,ArrowLeft:263,ArrowDown:264,ArrowUp:265,ShiftLeft:340,ControlLeft:341,AltLeft:342,ShiftRight:344,ControlRight:345}[e.code]??(e.code==='Space'?32:e.key.length===1?e.key.toUpperCase().charCodeAt(0):-1));
export class Processing {
  constructor(host){this.host=host;this.module=host.newModule();this.events=new Map();this.eventQueue=[];this.keys=new Set();this.canvases=new Set();this.images=new Set();this.textCache=new Map();this.abort=new AbortController();this.running=false;this.looping=true;this.redraw=true;this.exiting=false;this.frameCount=0;this.fps=60;this.clock=performance.now();this.seed=1;this.noiseSeed=0;this.screen=new Canvas(this,640,480,false,this.module);this.bindRoot();this.input();}
  bindRoot(){const h=this.host,m=this.module,b=(n,f)=>h.bind(m,'Processing',n,f),s=(n,v)=>h.set(m,n,v);
    for(const [n,v] of Object.entries({CORNER:0,CORNERS:1,CENTER:2,RADIUS:3,RGB:0,HSB:1,ARGB:2,OPEN:0,CHORD:1,PIE:2,CLOSE:1,POINTS:0,LINES:1,TRIANGLES:4,TRIANGLE_STRIP:5,TRIANGLE_FAN:6,QUADS:7,QUAD_STRIP:8,POLYGON:9,LEFT:0,RIGHT:1,TOP:101,BOTTOM:102,BASELINE:103,ROUND:1,SQUARE:0,PROJECT:2,MITER:0,BEVEL:2,BLEND:0,ADD:1,MULTIPLY:2,SCREEN:3,REPLACE:4,GRAY:0,INVERT:1,THRESHOLD:2,POSTERIZE:3,OPAQUE:4,BLUR:5,NORMAL:0,IMAGE:1,ESC:256,SPACE:32,PI:Math.PI,TWO_PI:Math.PI*2,TAU:Math.PI*2,HALF_PI:Math.PI/2,QUARTER_PI:Math.PI/4,P2D:'P2D',P3D:'P3D',backend:'wgpu',frameCount:0,mouseX:0,mouseY:0,pmouseX:0,pmouseY:0,keyCode:0,key:'',mouseButton:0,wheelCount:0,isMousePressed:false,isKeyPressed:false,inputText:'',compositionText:'',compositionCursor:0,isComposing:false,textInputEnabled:false}))s(n,v);
    b('size',async(w,hh,renderer='P2D',title='Aquarius')=>{if(this.device)throw new Error('size() can only be called once');if(!['P2D','P3D'].includes(renderer))throw new Error('Invalid renderer');this.device=await h.graphics.createDevice();this.shader=await this.device.createShader(h.bundle.graphics.vertex,h.bundle.graphics.fragment);this.surface=h.surface(w,hh,title);this.surface.requestSize(w,hh);this.dom=this.surface.canvas;this.presentation=this.device.createSurface(this.dom);this.screen.is3D=renderer==='P3D';const size=this.surface.size;this.screen.resize(size.width,size.height,size.pixelWidth,size.pixelHeight);this.screen.defaultCamera();this.screen.drawing=true;this.clock=performance.now();});
    b('resize',(w,hh)=>{if(!this.surface)throw new Error('Call Processing.size() first');this.surface.requestSize(w,hh);});
    b('run',async(setup,draw)=>{if(this.running)throw new Error('run() cannot be nested');this.running=true;this.exiting=false;try{await h.vm.invoke(setup);if(!this.device)throw new Error('Call Processing.size() first');while(!this.exiting&&!h.signal.aborted){await h.nextFrame(this.fps);await this.beginFrame();if(this.exiting)break;if(this.screen.pixelWidth===0||this.screen.pixelHeight===0)continue;if(this.looping||this.redraw||this.frameCount===0){this.redraw=false;this.frameCount++;s('frameCount',num(this.frameCount,'int'));await h.vm.invoke(draw);await this.endFrame();if(h.frameLimit>0&&this.frameCount>=h.frameLimit)break;}}}finally{this.running=false;}});
    b('on',(name,fn)=>{if(fn?.type!=='closure'&&typeof fn!=='function')throw new Error('Expected a function callback');this.events.set(name,fn);});
    b('beginFrame',()=>this.beginFrame());b('endFrame',()=>this.endFrame());
    b('noLoop',()=>this.looping=false);b('loop',()=>this.looping=true);b('redraw',()=>this.redraw=true);b('exit',()=>this.exiting=true);b('close',()=>this.exiting=true);
    b('frameRate',fps=>{if(fps<=0||fps>1000)throw new Error('Invalid frame rate');this.fps=fps;});b('millis',()=>performance.now()-this.clock);b('keyDown',code=>this.keys.has(code));
    b('createGraphics',(w,hh,renderer='P2D')=>{if(!this.device)throw new Error('Call size() first');const c=new Canvas(this,w,hh,renderer==='P3D');c.resize(w,hh,w,hh);this.canvases.add(c);return c.module;});
    b('createImage',(w,hh,format=2)=>this.image(w,hh,null,format).module);b('loadImage',async path=>{const data=await h.imageBytes(path);return this.image(data.width,data.height,data.bytes).module;});
    b('createFont',(name,size)=>{const font=h.newModule();h.set(font,'name',name);h.set(font,'size',size);return font;});
    b('createShape',()=>this.retained());
    for(const n of ['abs','ceil','floor','round','sqrt','exp','log','sin','cos','tan','asin','acos','atan'])b(n,v=>{const r=Math[n](v);if(!Number.isFinite(r))throw new Error('Arguments outside domain');return ['ceil','floor','round'].includes(n)?num(r,'int'):r;});
    b('sq',v=>v*v);b('radians',v=>v*Math.PI/180);b('degrees',v=>v*180/Math.PI);b('pow',Math.pow);b('atan2',Math.atan2);b('min',(...a)=>Math.min(...(Array.isArray(a[0])?a[0]:a)));b('max',(...a)=>Math.max(...(Array.isArray(a[0])?a[0]:a)));b('constrain',clamp);b('lerp',mix);b('norm',(v,l,r)=>(v-l)/(r-l));b('map',(v,l,r,a,z)=>a+(v-l)/(r-l)*(z-a));b('dist',(...a)=>Math.hypot(...a.slice(0,a.length/2).map((v,i)=>v-a[i+a.length/2])));b('mag',(...a)=>Math.hypot(...a));
    b('randomSeed',n=>this.seed=n>>>0);const random=()=>{this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;};b('random',(a,b)=>Array.isArray(a)?a[Math.floor(random()*a.length)]:b===undefined?random()*a:mix(a,b,random()));b('randomGaussian',()=>Math.sqrt(-2*Math.log(1-random()))*Math.cos(2*Math.PI*random()));
    b('noiseSeed',n=>this.noiseSeed=n);b('noiseDetail',(n,f=.5)=>{this.noiseOctaves=n;this.noiseFalloff=f;});b('noise',(x,y=0,z=0)=>this.noise(x,y,z));
    b('bezierPoint',bez);b('curvePoint',curve);b('bezierTangent',(a,b,c,d,t)=>3*(1-t)**2*(b-a)+6*(1-t)*t*(c-b)+3*t*t*(d-c));b('curveTangent',(a,b,c,d,t)=>(curve(a,b,c,d,t+.0001)-curve(a,b,c,d,t-.0001))/.0002);
    b('createVector',(...a)=>this.vector(a));b('PVector',(...a)=>this.vector(a));
    b('startTextInput',()=>{s('textInputEnabled',true);this.textarea.focus();});b('stopTextInput',()=>{s('textInputEnabled',false);this.textarea.blur();});b('textInputRect',(x,y,w,hh)=>Object.assign(this.textarea.style,{left:`${x}px`,top:`${y}px`,width:`${w}px`,height:`${hh}px`}));
    b('noCursor',()=>this.dom.style.cursor='none');b('cursor',()=>this.dom.style.cursor='');b('fullScreen',async(renderer='P2D',title)=>{await m.scope.get('size')(num(window.innerWidth,'int'),num(window.innerHeight,'int'),renderer,title??'Aquarius');});
  }
  noise(x,y,z){const hash=(x,y,z)=>{let h=Math.imul(x^this.noiseSeed,374761393)+Math.imul(y,668265263)+Math.imul(z,2147483647);h=Math.imul(h^(h>>>13),1274126177);return ((h^(h>>>16))>>>0)/4294967296;};const smooth=t=>t*t*(3-2*t);let total=0,amp=.5,sum=0;for(let octave=0;octave<(this.noiseOctaves??4);octave++){const a=Math.floor(x),b=Math.floor(y),c=Math.floor(z),tx=smooth(x-a),ty=smooth(y-b),tz=smooth(z-c);let layers=[];for(let k=0;k<2;k++)layers.push(mix(mix(hash(a,b,c+k),hash(a+1,b,c+k),tx),mix(hash(a,b+1,c+k),hash(a+1,b+1,c+k),tx),ty));total+=mix(...layers,tz)*amp;sum+=amp;amp*=this.noiseFalloff??.5;x*=2;y*=2;z*=2;}return total/sum;}
  vector(a){let v=vec3.fromValues(a[0]??0,a[1]??0,a[2]??0);const h=this.host,m=h.newModule(),update=()=>['x','y','z'].forEach((n,i)=>h.set(m,n,v[i]));const bind=(n,f)=>h.bind(m,'PVector',n,f);const read=o=>Array.isArray(o)?o:[unwrap(o.scope.get('x')),unwrap(o.scope.get('y')),unwrap(o.scope.get('z'))];
    for(const [n,fn] of Object.entries({set:(...a)=>{v=vec3.fromValues(...(a.length===1?read(a[0]):[a[0],a[1],a[2]??0]));},add:o=>vec3.add(v,v,read(o)),sub:o=>vec3.sub(v,v,read(o)),mult:n=>vec3.scale(v,v,n),div:n=>vec3.scale(v,v,1/n),normalize:()=>vec3.normalize(v,v),setMag:n=>{vec3.normalize(v,v);vec3.scale(v,v,n);},limit:n=>{if(vec3.length(v)>n){vec3.normalize(v,v);vec3.scale(v,v,n);}},rotate:n=>vec3.rotateZ(v,v,[0,0,0],n),lerp:(o,t)=>vec3.lerp(v,v,read(o),t)}))bind(n,(...args)=>{fn(...args);update();return m;});
    bind('copy',()=>this.vector(v));bind('array',()=>Array.from(v));bind('mag',()=>vec3.length(v));bind('magSq',()=>vec3.squaredLength(v));bind('heading',()=>Math.atan2(v[1],v[0]));bind('dot',o=>vec3.dot(v,read(o)));bind('cross',o=>this.vector(vec3.cross(vec3.create(),v,read(o))));bind('dist',o=>vec3.distance(v,read(o)));bind('angleBetween',o=>vec3.angle(v,read(o)));update();return m;
  }
  image(w,h,data=null,format=2){if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>8192||h>8192||w*h>16*1024*1024)throw new Error('Invalid image dimensions');const host=this.host,m=host.newModule(),img={module:m,width:w,height:h,bytes:data??new Uint8Array(w*h*4),dirty:true};if(!data&&format===0)for(let i=3;i<img.bytes.length;i+=4)img.bytes[i]=255;this.images.add(img);host.objects.set(m,img);host.set(m,'width',num(w,'int'));host.set(m,'height',num(h,'int'));const b=(n,f)=>host.bind(m,'PImage',n,f);
    b('loadPixels',()=>host.set(m,'pixels',Array.from({length:w*h},(_,i)=>num(pack(Array.from(img.bytes.subarray(i*4,i*4+4),v=>v/255))))));
    b('updatePixels',()=>{const pixels=m.scope.get('pixels');if(pixels.length!==w*h)throw new Error('Pixel count must match image');for(let i=0;i<pixels.length;i++)img.bytes.set(unpack(unwrap(pixels[i])).map(v=>Math.round(v*255)),i*4);img.dirty=true;});
    b('set',(x,y,c)=>{if(x<0||y<0||x>=w||y>=h)return;img.bytes.set(unpack(c).map(v=>Math.round(v*255)),(y*w+x)*4);img.dirty=true;});b('get',(x,y)=>x===undefined?m:x<0||y<0||x>=w||y>=h?0:pack(Array.from(img.bytes.subarray((y*w+x)*4,(y*w+x+1)*4),v=>v/255)));b('save',path=>host.saveImage(path,w,h,img.bytes));
    b('filter',(kind,parameter=.5)=>{for(let i=0;i<img.bytes.length;i+=4){const gray=Math.round(img.bytes[i]*.299+img.bytes[i+1]*.587+img.bytes[i+2]*.114);if(kind===0||kind===2)img.bytes.fill(kind===2?(gray/255>=parameter?255:0):gray,i,i+3);if(kind===1)for(let j=0;j<3;j++)img.bytes[i+j]=255-img.bytes[i+j];if(kind===4)img.bytes[i+3]=255;}img.dirty=true;});return img;
  }
  retained(){const h=this.host,m=h.newModule(),shape={vertices:[],style:style(),matrix:mat4.create(),kind:9,closed:false,children:[]};h.objects.set(m,shape);const b=(n,f)=>h.bind(m,'PShape',n,f);b('beginShape',(kind=9)=>{shape.kind=kind;shape.vertices=[];});b('vertex',(...a)=>shape.vertices.push(point(a,a.length)));b('endShape',(close=0)=>shape.closed=close===1);b('fill',(...a)=>{shape.style.fill=color(shape.style,a);shape.style.hasFill=true;});b('stroke',(...a)=>shape.style.stroke=color(shape.style,a));b('noStroke',()=>shape.style.hasStroke=false);b('noFill',()=>shape.style.hasFill=false);b('strokeWeight',w=>shape.style.weight=w);b('getVertexCount',()=>num(shape.vertices.length,'int'));b('getVertex',i=>shape.vertices[i]);b('setVertex',(i,...v)=>shape.vertices[i]=point(v,v.length));b('setFill',c=>shape.style.fill=unpack(c));b('translate',(...a)=>mat4.translate(shape.matrix,shape.matrix,point(a,a.length)));b('rotate',n=>mat4.rotateZ(shape.matrix,shape.matrix,n));b('scale',n=>mat4.scale(shape.matrix,shape.matrix,[n,n,n]));b('resetMatrix',()=>shape.matrix=mat4.create());b('addChild',child=>{const obj=h.objects.get(child);const contains=s=>s===shape||s.children.some(contains);if(contains(obj))throw new Error('Shape groups cannot contain cycles');shape.children.push(obj);});return m;}
  input(){const h=this.host,s=(n,v)=>h.set(this.module,n,v),signal=this.abort.signal;const queue=(name,fields)=>this.eventQueue.push({name,fields});
    window.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT')return;const code=keyCode(e);this.keys.add(code);if(!e.isComposing&&!this.composing)queue('keyPressed',{keyCode:num(code,'int'),key:e.key,isKeyPressed:true});if(code===256&&!this.module.scope.get('textInputEnabled')&&!this.composing)this.exiting=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();},{signal});
    window.addEventListener('keyup',e=>{const code=keyCode(e);this.keys.delete(code);if(!e.isComposing&&!this.composing)queue('keyReleased',{keyCode:num(code,'int'),key:e.key,isKeyPressed:this.keys.size>0});},{signal});
    // CSS coordinates are already logical host coordinates. Scaling by the last
    // frame's dimensions would misplace events arriving during a viewport resize.
    const area=document.getElementById('surfaces');for(const type of ['pointermove','pointerdown','pointerup'])area.addEventListener(type,e=>{if(!this.dom)return;const r=this.dom.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const fields={pmouseX:this.module.scope.get('mouseX'),pmouseY:this.module.scope.get('mouseY'),mouseX:x,mouseY:y,mouseButton:num(e.button,'int')};if(type!=='pointermove')fields.isMousePressed=type==='pointerdown';queue(type==='pointerdown'?'mousePressed':type==='pointerup'?'mouseReleased':e.buttons?'mouseDragged':'mouseMoved',fields);if(type==='pointerup')queue('mouseClicked',fields);},{signal});
    area.addEventListener('wheel',e=>{queue('mouseWheel',{wheelCount:e.deltaY/100});e.preventDefault();},{signal,passive:false});
    this.textarea=document.createElement('textarea');Object.assign(this.textarea.style,{position:'fixed',opacity:'0.01',width:'1px',height:'1px',pointerEvents:'none'});this.textarea.setAttribute('aria-label','遊戲鍵盤輸入');document.body.append(this.textarea);
    this.textarea.addEventListener('input',e=>{if(!e.isComposing&&e.data){queue('textInput',{inputText:e.data});for(const char of e.data)queue('keyTyped',{key:char});this.textarea.value='';}},{signal});for(const [type,name] of [['compositionstart','compositionStarted'],['compositionupdate','compositionUpdated'],['compositionend','compositionEnded']])this.textarea.addEventListener(type,e=>{this.composing=type!=='compositionend';queue(name,{compositionText:this.composing?e.data:'',compositionCursor:this.composing?e.data.length:0,isComposing:this.composing});},{signal});
    s('textInputEnabled',false);
  }
  async beginFrame(){
    const c=this.screen;let resized=false;
    if(this.surface){const size=this.surface.readSize();resized=c.resize(size.width,size.height,size.pixelWidth,size.pixelHeight);this.surface.apply(size);}
    c.model=mat4.create();c.matrices=[];c.style.lights=[];c.style.lit=false;
    // Attachments and public dimensions are ready before callbacks can draw/read.
    if(resized){this.redraw=true;if(c.pixelWidth>0&&c.pixelHeight>0&&this.events.has('windowResized'))await this.host.vm.invoke(this.events.get('windowResized'));}
    for(const e of this.eventQueue.splice(0)){for(const [n,v] of Object.entries(e.fields))this.host.set(this.module,n,v);this.redraw=true;if(this.events.has(e.name))await this.host.vm.invoke(this.events.get(e.name));}
  }
  async endFrame(){if(this.screen.pixelWidth>0&&this.screen.pixelHeight>0)await this.presentation.present(this.screen.target);}
  dispose(){this.exiting=true;this.abort.abort();this.textarea.remove();for(const c of this.canvases)c.dispose();for(const image of this.images)image.texture?.destroy();for(const t of this.textCache.values())t.texture.destroy();this.screen.dispose();this.presentation?.dispose();this.surface?.dispose();}
}
class Canvas {
  constructor(owner,w,h,is3D,module=null){this.owner=owner;this.host=owner.host;this.module=module??this.host.newModule();this.host.objects.set(this.module,this);this.width=this.pixelWidth=w;this.height=this.pixelHeight=h;this.is3D=is3D;this.style=style();this.model=mat4.create();this.view=mat4.create();this.projection=mat4.create();this.matrices=[];this.styles=[];this.sphereU=24;this.sphereV=16;this.vertices=null;this.blend=0;this.drawing=module!==null;this.disposed=false;this.defaultCamera();this.bind();this.state();}
  state(){for(const n of ['width','height','pixelWidth','pixelHeight'])this.host.set(this.module,n,num(this[n],'int'));}
  live(){if(this.disposed)throw new Error('Canvas is disposed');if(!this.target||!this.drawing)throw new Error('Call size() or beginDraw() first');}
  resize(w,h,pw=w,ph=h){
    if(this.disposed)throw new Error('Canvas is disposed');
    if(this.drawing&&this!==this.owner.screen)throw new Error('resize() requires endDraw()');
    const next=resizeSurfaceSize(this,w,h,pw,ph),logical=next.width!==this.width||next.height!==this.height;
    const changed=logical||next.pixelWidth!==this.pixelWidth||next.pixelHeight!==this.pixelHeight;
    const drawable=next.pixelWidth>0&&next.pixelHeight>0;
    if(drawable&&(!this.target||this.target.width!==next.pixelWidth||this.target.height!==next.pixelHeight)){
      const target=this.owner.device.createTarget(next.pixelWidth,next.pixelHeight);this.target?.dispose();this.target=target;
    }
    Object.assign(this,next);if(logical)this.defaultCamera();
    if(changed)this.host.set(this.module,'pixels',null);
    this.state();return changed;
  }
  defaultCamera(){this.model=mat4.create();if(this.is3D){const z=this.height/2/Math.tan(Math.PI/6);mat4.lookAt(this.view,[this.width/2,this.height/2,z],[this.width/2,this.height/2,0],[0,1,0]);mat4.perspectiveNO(this.projection,Math.PI/3,this.width/this.height,z/10,z*10);this.projection[5]*=-1;}else{this.view=mat4.create();mat4.orthoNO(this.projection,0,this.width,this.height,0,-10000,10000);}}
  textRasterScale(x,y){
    const matrix=mat4.multiply(mat4.create(),this.projection,mat4.multiply(mat4.create(),this.view,this.model));
    const project=(x,y)=>{const p=vec4.transformMat4(vec4.create(),[x,y,0,1],matrix);return [p[0]/p[3]*this.pixelWidth/2,p[1]/p[3]*this.pixelHeight/2];};
    const origin=project(x,y),dx=project(x+1,y),dy=project(x,y+1);
    const scale=Math.max(Math.hypot(dx[0]-origin[0],dx[1]-origin[1]),Math.hypot(dy[0]-origin[0],dy[1]-origin[1]));
    return Number.isFinite(scale)?clamp(Math.round(scale*1000)/1000,1,8):1;
  }
  uniforms(texture,lit){const s=this.style,u=defaultUniforms(this.host.bundle.graphics);u.set(this.model);u.set(this.view,16);u.set(this.projection,32);const normal=mat4.multiply(mat4.create(),this.view,this.model);mat4.invert(normal,normal);mat4.transpose(normal,normal);u.set(normal,48);u.set([texture?1:0,s.lit&&lit?1:0,texture?.premultiplied?1:0,this.blend===4?1:0],64);u.set(s.ambient,68);u.set(s.specular,72);u.set(s.emissive,76);u.set(s.material,80);u[84]=s.lights.length;for(let i=0;i<s.lights.length;i++){const l=s.lights[i];u.set([...l.color,l.kind,...l.position,0,...l.direction,0,...l.falloff,0,...l.specular,0,l.cutoff??0,l.concentration??0,0,0],88+i*24);}return u;}
  draw(vertices,texture=null,lit=true,mode=4){this.live();if(!vertices.length||this.pixelWidth===0||this.pixelHeight===0)return;let gpuTexture;if(texture instanceof Canvas){texture.target.flush();gpuTexture=texture.target.color;}else if(texture){if(!texture.texture)texture.texture=this.owner.device.texture(texture.width,texture.height,texture.bytes);else if(texture.dirty){this.target.flush();this.owner.device.gpu.queue.writeTexture({texture:texture.texture},texture.bytes,{bytesPerRow:texture.width*4},[texture.width,texture.height]);}texture.dirty=false;gpuTexture=texture.texture;}const clip=this.clip?.map((v,i)=>v*(i%2===0?this.pixelWidth/this.width:this.pixelHeight/this.height));this.target.draw(this.shader??this.owner.shader,vertices.flat(),this.uniforms(texture,lit),this.is3D,gpuTexture,this.blend,mode,clip);}
  vertex(p,c=this.style.fill,uv=[0,0],normal=[0,0,1]){return [...p,...normal,...uv,...c];}
  polygon(points,closed=true,fill=true,holes=[]){if(points.length>=3&&this.style.hasFill&&fill){const coords=points.flatMap(p=>p.slice(0,2)),ids=[];for(const hole of holes){ids.push(coords.length/2);coords.push(...hole.flatMap(p=>p.slice(0,2)));}const all=[...points,...holes.flat()];this.draw(earcut(coords,ids).map(i=>this.vertex(all[i])),null,false);}if(this.style.hasStroke){this.polyline(points,closed);for(const hole of holes)this.polyline(hole,true);}}
  polyline(points,closed=false){if(!this.style.hasStroke)return;for(let i=0;i<points.length-(closed?0:1);i++)this.segment(points[i],points[(i+1)%points.length]);}
  segment(a,b){if(!this.style.hasStroke)return;const dx=b[0]-a[0],dy=b[1]-a[1],length=Math.hypot(dx,dy);if(!length)return;const x=-dy/length*this.style.weight/2,y=dx/length*this.style.weight/2,p=[[a[0]+x,a[1]+y,a[2]],[b[0]+x,b[1]+y,b[2]],[b[0]-x,b[1]-y,b[2]],[a[0]-x,a[1]-y,a[2]]];this.draw([0,1,2,0,2,3].map(i=>this.vertex(p[i],this.style.stroke)),null,false);}
  bind(){const h=this.host,m=this.module,b=(n,f)=>h.bind(m,this===this.owner.screen?'Processing':'Processing.Canvas',n,f),s=this;
    b('resize',(...a)=>{if(a.length!==2&&a.length!==4)throw new Error('resize() takes two or four dimensions');if(a.some(v=>!Number.isInteger(v)||v<1||v>8192))throw new Error('Dimension must be 1..8192');return s.resize(...a);});b('beginDraw',()=>{if(s.drawing)throw new Error('beginDraw() is already active');s.drawing=true;s.model=mat4.create();});b('endDraw',()=>{s.live();s.target.flush();s.drawing=false;});b('dispose',()=>s.dispose());
    b('colorMode',(mode,...a)=>{s.style.colorMode=mode;if(a.length===1)s.style.colorMax=[a[0],a[0],a[0],a[0]];else if(a.length>=3)s.style.colorMax=[...a.slice(0,3),a[3]??s.style.colorMax[3]];});b('color',(...a)=>pack(color(s.style,a)));b('lerpColor',(a,b,t)=>pack(unpack(a).map((v,i)=>mix(v,unpack(b)[i],clamp(t)))));
    for(const [name,index] of [['red',0],['green',1],['blue',2],['alpha',3]])b(name,c=>unpack(c)[index]*s.style.colorMax[index]);
    b('fill',(...a)=>{s.style.fill=color(s.style,a);s.style.hasFill=true;});b('stroke',(...a)=>{s.style.stroke=color(s.style,a);s.style.hasStroke=true;});b('noFill',()=>s.style.hasFill=false);b('noStroke',()=>s.style.hasStroke=false);b('tint',(...a)=>s.style.tint=color(s.style,a));b('noTint',()=>s.style.tint=[1,1,1,1]);b('strokeWeight',w=>s.style.weight=w);
    for(const n of ['rectMode','ellipseMode','imageMode'])b(n,v=>s.style[n]=v);b('strokeCap',v=>s.style.cap=v);b('strokeJoin',v=>s.style.join=v);
    b('background',(...a)=>{s.live();s.target.clear(color(s.style,a));});b('clear',()=>{s.live();s.target.clear([0,0,0,0]);});
    b('line',(...a)=>s.segment(point(a,a.length/2),point(a.slice(a.length/2),a.length/2)));b('triangle',(...a)=>s.polygon([point(a),point(a.slice(2)),point(a.slice(4))]));b('quad',(...a)=>s.polygon([0,2,4,6].map(i=>point(a.slice(i)))));
    b('rect',(x,y,w,h,r=0)=>{[x,y,w,h]=bounds(x,y,w,h,s.style.rectMode);const pts=[];r=Math.max(0,Math.min(r,Math.abs(w)/2,Math.abs(h)/2));if(r)for(let c=0;c<4;c++){const cx=c<2?x+w-r:x+r,cy=c===1||c===2?y+h-r:y+r;for(let i=0;i<=8;i++){const a=-Math.PI/2+c*Math.PI/2+i*Math.PI/16;pts.push([cx+r*Math.cos(a),cy+r*Math.sin(a),0]);}}else pts.push([x,y,0],[x+w,y,0],[x+w,y+h,0],[x,y+h,0]);s.polygon(pts);});b('square',(x,y,w)=>m.scope.get('rect')(num(x),num(y),num(w),num(w)));
    const ellipse=(x,y,w,h,start=0,stop=2*Math.PI,mode=1)=>{[x,y,w,h]=bounds(x,y,w,h,s.style.ellipseMode);const pts=[];if(mode===2)pts.push([x+w/2,y+h/2,0]);for(let i=0;i<=64;i++){const a=mix(start,stop,i/64);pts.push([x+w/2+w/2*Math.cos(a),y+h/2+h/2*Math.sin(a),0]);}s.polygon(pts,mode!==0,mode!==0);};b('ellipse',ellipse);b('circle',(x,y,d)=>ellipse(x,y,d,d));b('arc',ellipse);b('point',(x,y,z=0)=>{const saved=s.style.fill;s.style.fill=s.style.stroke;const pts=[];for(let i=0;i<16;i++)pts.push([x+Math.cos(i*Math.PI/8)*s.style.weight/2,y+Math.sin(i*Math.PI/8)*s.style.weight/2,z]);s.polygon(pts);s.style.fill=saved;});
    for(const [n,fn] of [['bezier',bez],['curve',curve]])b(n,(...a)=>{const d=a.length/4,p=Array.from({length:4},(_,i)=>point(a.slice(i*d),d)),pts=[];for(let i=0;i<=32;i++)pts.push([0,1,2].map(j=>fn(...p.map(v=>v[j]),i/32)));s.polyline(pts);});b('bezierDetail',v=>s.detail=v);b('curveDetail',v=>s.detail=v);b('curveTightness',v=>s.tightness=v);
    b('pushMatrix',()=>s.matrices.push(mat4.clone(s.model)));b('popMatrix',()=>{if(!s.matrices.length)throw new Error('Matrix stack is empty');s.model=s.matrices.pop();});b('resetMatrix',()=>s.model=mat4.create());b('pushStyle',()=>s.styles.push(structuredClone(s.style)));b('popStyle',()=>{if(!s.styles.length)throw new Error('Style stack is empty');s.style=s.styles.pop();});b('push',()=>{s.matrices.push(mat4.clone(s.model));s.styles.push(structuredClone(s.style));});b('pop',()=>{if(!s.matrices.length||!s.styles.length)throw new Error('push/pop stack is empty');s.model=s.matrices.pop();s.style=s.styles.pop();});
    b('translate',(...a)=>mat4.translate(s.model,s.model,point(a,a.length)));b('scale',(...a)=>mat4.scale(s.model,s.model,a.length===1?[a[0],a[0],a[0]]:[a[0],a[1],a[2]??1]));b('rotate',r=>mat4.rotateZ(s.model,s.model,r));for(const axis of ['X','Y','Z'])b(`rotate${axis}`,r=>mat4[`rotate${axis}`](s.model,s.model,r));b('applyMatrix',m=>mat4.multiply(s.model,s.model,m));b('getMatrix',()=>Array.from(s.model));
    b('camera',(...a)=>{if(!a.length)s.defaultCamera();else mat4.lookAt(s.view,a.slice(0,3),a.slice(3,6),a.slice(6,9));});b('perspective',(fov=Math.PI/3,aspect=s.width/s.height,near=1,far=10000)=>{mat4.perspectiveNO(s.projection,fov,aspect,near,far);s.projection[5]*=-1;});b('ortho',(l=0,r=s.width,b=s.height,t=0,n=-10000,f=10000)=>mat4.orthoNO(s.projection,l,r,b,t,n,f));
    b('lights',()=>{s.style.lit=true;s.style.ambient=[.5,.5,.5];s.style.lights=[{kind:0,color:[.5,.5,.5],position:[0,0,0],direction:[0,0,-1],falloff:[1,0,0],specular:[0,0,0]}];});b('noLights',()=>{s.style.lit=false;s.style.lights=[];s.style.ambient=[0,0,0];});b('ambientLight',(...a)=>{s.style.lit=true;s.style.ambient=color(s.style,a).slice(0,3);});
    for(const [n,kind] of [['directionalLight',0],['pointLight',1],['spotLight',2]])b(n,(...a)=>{if(s.style.lights.length>=8)throw new Error('Too many lights');s.style.lit=true;s.style.lights.push({kind,color:color(s.style,a.slice(0,3)).slice(0,3),position:kind===0?[0,0,0]:a.slice(3,6),direction:kind===0?a.slice(3,6):kind===2?a.slice(6,9):[0,0,1],falloff:s.style.falloff,specular:s.style.lightSpecular,cutoff:Math.cos(a[9]??0),concentration:a[10]??0});});
    b('lightFalloff',(...a)=>s.style.falloff=a);b('lightSpecular',(...a)=>s.style.lightSpecular=color(s.style,a).slice(0,3));for(const n of ['specular','emissive'])b(n,(...a)=>s.style[n]=color(s.style,a).slice(0,3));b('ambient',(...a)=>s.style.material.splice(0,3,...color(s.style,a).slice(0,3)));b('shininess',v=>s.style.material[3]=v);
    b('box',(w,h=w,d=w)=>{const p=[[-w,-h,-d],[w,-h,-d],[w,h,-d],[-w,h,-d],[-w,-h,d],[w,-h,d],[w,h,d],[-w,h,d]].map(p=>p.map(x=>x/2)),faces=[[4,5,6,7],[1,0,3,2],[0,4,7,3],[5,1,2,6],[3,7,6,2],[0,1,5,4]],normals=[[0,0,1],[0,0,-1],[-1,0,0],[1,0,0],[0,1,0],[0,-1,0]],verts=[];if(s.style.hasFill){faces.forEach((f,j)=>[0,1,2,0,2,3].forEach(i=>verts.push(s.vertex(p[f[i]],s.style.fill,[0,0],normals[j]))));s.draw(verts);}if(s.style.hasStroke)faces.forEach(f=>s.polyline(f.map(i=>p[i]),true));});
    b('sphereDetail',(u,v=u)=>{s.sphereU=u;s.sphereV=v;});b('sphere',r=>{const p=(u,v)=>{const a=u*Math.PI*2/s.sphereU,b=v*Math.PI/s.sphereV;return [Math.sin(b)*Math.cos(a),Math.cos(b),Math.sin(b)*Math.sin(a)];},verts=[];for(let v=0;v<s.sphereV;v++)for(let u=0;u<s.sphereU;u++){const a=p(u,v),b=p(u+1,v),c=p(u+1,v+1),d=p(u,v+1);for(const n of [a,b,c,a,c,d])verts.push(s.vertex(n.map(v=>v*r),s.style.fill,[0,0],n));}if(s.style.hasFill)s.draw(verts);});
    b('beginShape',(kind=9)=>{if(s.vertices)throw new Error('Shape already active');s.kind=kind;s.vertices=[];s.holes=[];s.contour=null;});b('vertex',(...a)=>{if(!s.vertices)throw new Error('Call beginShape() first');(s.contour??s.vertices).push(point(a,a.length===3||a.length===5?3:2));});b('beginContour',()=>{s.contour=[];s.holes.push(s.contour);});b('endContour',()=>s.contour=null);b('endShape',(close=0)=>{const v=s.vertices;s.vertices=null;if(!v)throw new Error('Call beginShape() first');if(s.kind===9)s.polygon(v,close===1,true,s.holes);else {const indices=[];if(s.kind===4)for(let i=0;i<v.length;i++)indices.push(i);if(s.kind===5)for(let i=2;i<v.length;i++)indices.push(i-2,i-1,i);if(s.kind===6)for(let i=2;i<v.length;i++)indices.push(0,i-1,i);if(s.kind===7)for(let i=0;i<v.length;i+=4)indices.push(i,i+1,i+2,i,i+2,i+3);s.draw(indices.map(i=>s.vertex(v[i])));}});
    b('shape',(shape,x=0,y=0)=>{const obj=h.objects.get(shape),savedStyle=s.style,savedMatrix=s.model;const render=obj=>{s.model=mat4.multiply(mat4.create(),s.model,obj.matrix);s.style=obj.style;s.polygon(obj.vertices,obj.closed);for(const child of obj.children)render(child);};s.model=mat4.translate(mat4.clone(s.model),s.model,[x,y,0]);render(obj);s.model=savedMatrix;s.style=savedStyle;});
    b('image',(image,x,y,w,hh)=>{const img=h.objects.get(image);if(!img)throw new Error('Expected image');w??=img.width;hh??=img.height;[x,y,w,hh]=bounds(x,y,w,hh,s.style.imageMode);s.draw([[x,y,0,0,0],[x+w,y,0,1,0],[x+w,y+hh,0,1,1],[x,y,0,0,0],[x+w,y+hh,0,1,1],[x,y+hh,0,0,1]].map(p=>s.vertex(p.slice(0,3),s.style.tint,p.slice(3))),img,false);});
    b('createShader',async(v,f)=>this.shaderModule(await s.owner.device.createShader(v,f)));
    b('loadShader',async(fragment,vertex)=>{const text=path=>new TextDecoder().decode(h.asset(path));return this.shaderModule(await s.owner.device.createShader(vertex===undefined?h.bundle.graphics.vertex:text(vertex),text(fragment)));});
    b('shader',m=>s.shader=h.objects.get(m));b('resetShader',()=>s.shader=null);
    b('textFont',(font,size)=>{s.style.font=typeof font==='string'?font:font.scope.get('name');s.style.textSize=size??(typeof font==='string'?s.style.textSize:unwrap(font.scope.get('size')));});b('textSize',n=>{s.style.textSize=n;s.style.leading=n*1.2;});b('textLeading',n=>s.style.leading=n);b('textAlign',(a,v=103)=>{s.style.align=a;s.style.vertical=v;});
    const measure=t=>{const c=document.createElement('canvas').getContext('2d');c.font=`${s.style.textSize}px ${s.style.font}`;return c.measureText(String(t));};b('textWidth',t=>measure(t).width);b('textAscent',()=>s.style.textSize*.8);b('textDescent',()=>s.style.textSize*.2);
    b('text',(text,x,y,w,hh)=>{text=String(text);const st=s.style,density=s.textRasterScale(x,y),key=JSON.stringify([text,st.font,st.textSize,st.leading,st.fill,density]);let img=s.owner.textCache.get(key);if(!img){const lines=text.split('\n'),canvas=document.createElement('canvas'),width=Math.max(1,Math.ceil(Math.max(...lines.map(l=>measure(l).width)))+4),height=Math.max(1,Math.ceil(lines.length*st.leading+4));canvas.width=Math.ceil(width*density);canvas.height=Math.ceil(height*density);const ctx=canvas.getContext('2d');ctx.scale(density,density);ctx.font=`${st.textSize}px ${st.font}`;ctx.fillStyle=`rgba(${st.fill.slice(0,3).map(v=>Math.round(v*255)).join(',')},${st.fill[3]})`;ctx.textBaseline='top';lines.forEach((l,i)=>ctx.fillText(l,2,i*st.leading+2));const bytes=ctx.getImageData(0,0,canvas.width,canvas.height).data;img={width,height,texture:s.owner.device.texture(canvas.width,canvas.height,bytes)};s.owner.textCache.set(key,img);if(s.owner.textCache.size>256){const oldest=s.owner.textCache.keys().next().value,old=s.owner.textCache.get(oldest);s.owner.device.flush();old.texture.destroy();s.owner.device.resources.delete(old.texture);s.owner.textCache.delete(oldest);}}
      const left=x-(st.align===2?img.width/2:st.align===1?img.width:0),top=y-(st.vertical===103?st.textSize*.8:st.vertical===2?img.height/2:st.vertical===102?img.height:0);s.draw([[left,top,0,0,0],[left+img.width,top,0,1,0],[left+img.width,top+img.height,0,1,1],[left,top,0,0,0],[left+img.width,top+img.height,0,1,1],[left,top+img.height,0,0,1]].map(p=>s.vertex(p.slice(0,3),[1,1,1,1],p.slice(3))),img,false);});
    b('save',async path=>h.saveImage(path,s.pixelWidth,s.pixelHeight,await s.target.readPixels()));b('saveFrame',async path=>h.saveImage(path.replace(/#+/,x=>String(s.owner.frameCount).padStart(x.length,'0')),s.pixelWidth,s.pixelHeight,await s.target.readPixels()));
    b('loadPixels',async()=>{const bytes=await s.target.readPixels();h.set(m,'pixels',Array.from({length:bytes.length/4},(_,i)=>num(pack(Array.from(bytes.subarray(i*4,i*4+4),v=>v/255)))));});b('updatePixels',()=>{const bytes=new Uint8Array(s.pixelWidth*s.pixelHeight*4),p=m.scope.get('pixels');if(!Array.isArray(p)||p.length!==s.pixelWidth*s.pixelHeight)throw new Error('Call loadPixels() at the current resolution before updatePixels()');p.forEach((v,i)=>bytes.set(unpack(unwrap(v)).map(v=>Math.round(v*255)),i*4));s.target.flush();s.owner.device.gpu.queue.writeTexture({texture:s.target.color},bytes,{bytesPerRow:s.pixelWidth*4},[s.pixelWidth,s.pixelHeight]);});
    b('get',async(x,y)=>{const bytes=await s.target.readPixels();if(x===undefined){const logical=new Uint8Array(s.width*s.height*4);for(let y=0;y<s.height;y++)for(let x=0;x<s.width;x++){const i=(Math.floor(y*s.pixelHeight/s.height)*s.pixelWidth+Math.floor(x*s.pixelWidth/s.width))*4;logical.set(bytes.subarray(i,i+4),(y*s.width+x)*4);}return s.owner.image(s.width,s.height,logical).module;}if(x<0||y<0||x>=s.width||y>=s.height)return 0;const i=(Math.floor(y*s.pixelHeight/s.height)*s.pixelWidth+Math.floor(x*s.pixelWidth/s.width))*4;return pack(Array.from(bytes.subarray(i,i+4),v=>v/255));});
    b('blendMode',n=>s.blend=n);b('clip',(...a)=>s.clip=a);b('noClip',()=>s.clip=null);b('smooth',()=>{});b('noSmooth',()=>{});
  }
  shaderModule(shader){const h=this.host,m=h.newModule();h.objects.set(m,shader);h.bind(m,'PShader','set',(name,...v)=>shader.set(name,v.length===1&&Array.isArray(v[0])?v[0]:v));h.bind(m,'PShader','setInt',(name,v)=>shader.set(name,[v],true));return m;}
  dispose(){if(this.disposed)return;this.target?.dispose();this.disposed=true;}
}


